spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/almatestdb
    username: alma
    password: alma
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true